/* autogenerated do not edit */
#ifndef __TESTSUITE_TAGS_H__
#define __TESTSUITE_TAGS_H__
#include "xmlhandler.h"
extern const xml::tag_map_definition_t  testsuitetags[];
enum {
XML_testsuite = 1,
XML_test = 2,
XML_name = 3,
XML_file = 4,
XML_source = 5,
XML_results = 6,
XML_rawType = 7,
XML_thumbNum = 8,
XML_thumbSizes = 9,
XML_thumbFormats = 10,
XML_thumbDataSizes = 11,
XML_rawDataType = 12,
XML_rawDataSize = 13,
XML_rawDataDimensions = 14,
XML_rawCfaPattern = 15,
XML_rawMd5 = 16,
XML_rawDecompressedMd5 = 17,
XML_metaOrientation = 18,
XML_ = 19,
_XML_LASTTOKEN
};
#endif
