/* autogenerated do not edit */
#ifndef __TESTSUITE_TAGS_H__
#define __TESTSUITE_TAGS_H__
#include "xmlhandler.h"
extern const xml::tag_map_definition_t  testsuitetags[];
enum {
XML_testsuite = 1,
XML_test = 2,
XML_name = 3,
XML_file = 4,
XML_source = 5,
XML_results = 6,
XML_rawType = 7,
XML_rawTypeId = 8,
XML_thumbNum = 9,
XML_thumbSizes = 10,
XML_thumbFormats = 11,
XML_thumbDataSizes = 12,
XML_rawDataType = 13,
XML_rawDataSize = 14,
XML_rawDataDimensions = 15,
XML_rawCfaPattern = 16,
XML_rawMinValue = 17,
XML_rawMaxValue = 18,
XML_rawMd5 = 19,
XML_rawDecompressedMd5 = 20,
XML_metaOrientation = 21,
XML_ = 22,
_XML_LASTTOKEN
};
#endif
