/* autogenerated do not edit */
#include "testsuitetags.h"
const xml::tag_map_definition_t  testsuitetags[] = { 
{ "testsuite" , XML_testsuite },
{ "test" , XML_test },
{ "name" , XML_name },
{ "file" , XML_file },
{ "source" , XML_source },
{ "results" , XML_results },
{ "rawType" , XML_rawType },
{ "rawTypeId" , XML_rawTypeId },
{ "thumbNum" , XML_thumbNum },
{ "thumbSizes" , XML_thumbSizes },
{ "thumbFormats" , XML_thumbFormats },
{ "thumbDataSizes" , XML_thumbDataSizes },
{ "rawDataType" , XML_rawDataType },
{ "rawDataSize" , XML_rawDataSize },
{ "rawDataDimensions" , XML_rawDataDimensions },
{ "rawCfaPattern" , XML_rawCfaPattern },
{ "rawMinValue" , XML_rawMinValue },
{ "rawMaxValue" , XML_rawMaxValue },
{ "rawMd5" , XML_rawMd5 },
{ "rawDecompressedMd5" , XML_rawDecompressedMd5 },
{ "metaOrientation" , XML_metaOrientation },
{ "" , XML_ },
{ 0, 0 }
};
